version: "3.3"

services:
        
        portainer:
                image: "portainer/portainer-ce:latest"
                command: "-H unix:///var/run/docker.sock"
                container_name: "portainer"
                restart: unless-stopped
                volumes:
                        - "/var/run/docker.sock:/var/run/docker.sock"
                        - "/home/pi/.docker/portainer/data:/data"
                networks:
                        - traefik_net
                labels:
                        #Frontend
                        - "traefik.enable=true"
                        - "traefik.http.routers.portainer.rule=Host(`portainer.penguin-slap.de`)"
                        - "traefik.http.routers.portainer.entrypoints=websecure"
                        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
                        - "traefik.http.routers.portainer.service=portainer"
                        - "traefik.http.routers.portainer.tls.certResolver=letsencrypt"

                        #Edge
                        #- "traefik.http.routers.portainer.rule=Host(`edge.penguin-slap.de`)"
                        #- "traefik.http.routers.portainer.entrypoints=websecure"
                        #- "traefik.http.services.portainer.loadbalancer.server.port=8000"
                        #- "traefik.http.routers.portainer.service=edge"
                        #- "traefik.http.routers.portainer.tls.certResolver=letsencrypt"

networks:
        traefik_net:
                external:
                                true
